version: '3.8'
services:
  auth_app_dev:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    container_name: auth_app_dev
    ports:
      - '5173:5173'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env.development
    environment:
      - NODE_ENV=development
      - AUTH_MONGODB_URI=mongodb://auth_mongo_dev:27017/auth_db_dev
    depends_on:
      - auth_mongo_dev
    networks:
      - dev_network

  event_app_dev:
    build:
      context: .
      dockerfile: ./apps/event/Dockerfile
    container_name: event_app_dev
    ports:
      - '6173:6173'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env.development
    environment:
      - NODE_ENV=development
      - EVENT_MONGODB_URI=mongodb://event_mongo_dev:27017/event_db_dev?replicaSet=rsEvent
      - AUTH_SERVICE_URL=http://auth_app_dev:5173
    depends_on:
      event_mongo_dev_init:
        condition: service_completed_successfully
    networks:
      - dev_network

  auth_mongo_dev:
    image: mongo:latest
    hostname: auth_mongo_dev
    container_name: auth_mongo_dev
    ports:
      - '27017:27017'
    volumes:
      - auth_mongo_dev_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: auth_db_dev
    networks:
      - dev_network

  event_mongo_dev:
    image: mongo:latest
    hostname: event_mongo_dev
    container_name: event_mongo_dev
    ports:
      - '27018:27017'
    volumes:
      - event_mongo_dev_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: event_db_dev
    command: mongod --replSet rsEvent --bind_ip_all
    networks:
      - dev_network

  event_mongo_dev_init:
    image: mongo:latest
    container_name: event_rs_init_dev
    depends_on:
      - event_mongo_dev
    volumes:
      - ./scripts/init-event-rs.sh:/usr/local/bin/init-event-rs.sh
    entrypoint: ['/usr/local/bin/init-event-rs.sh']
    networks:
      - dev_network

volumes:
  auth_mongo_dev_data:
  event_mongo_dev_data:

networks:
  dev_network:
    driver: bridge
