#!/bin/bash

current_branch=$(git rev-parse --abbrev-ref HEAD)

echo "🔍 Pre-commit Hook: Running lint checks..."
if yarn lint-staged; then
  echo "✅ Lint checks passed."
else
  echo "❌ Lint checks failed. Aborting commit."
  exit 1
fi

if [[ "$current_branch" == "main" ]]; then
  echo "🔍 Pre-commit Hook: Running test checks on branch [$current_branch]..."
  if yarn test; then
    echo "✅ Test checks passed."
  else
    echo "❌ Test checks failed. Aborting commit."
    exit 1
  fi
else
  echo "🟡 Skipping tests on branch [$current_branch]."
fi